name: homework-6
on: push

jobs:
cypress-run:
runs-on: ubuntu-latest
steps:
name: Checkout
users: actions/checkout@v3
name: Cypress run
users:cypress-io/github-action@v5
with:
build: npm run build
start: npm start